server:
  port: 8082

spring:
  application:
    name: money-service
  cloud:
    nacos:
      discovery:
        # 确保这里的地址是实际 Nacos 服务器的地址
        server-addr: ${NACOS_ADDR:192.168.2.20:8848}

  jackson:
    generator:
      write_numbers_as_strings: true

#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://${MYSQL_HOST:192.168.2.20}:3306/matchmaker?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
#    username: root
#    password: 123456

  redis:
    host: ${REDIS_HOST:192.168.2.20}
    port: 6379
    password: ${REDIS_PASSWORD:123456}
    database: 0
    timeout: 3000ms
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
  #  redis:
  #    # 基本配置
  #    cluster:
  #      nodes:
  #        - 192.168.1.101:6379
  #        - 192.168.1.102:6379
  #        - 192.168.1.103:6379
  #      max-redirects: 3
  #    password: "your_password"
  #    timeout: 3000ms
  #
  #    # Redisson 配置
  #    redisson:
  #      config: |
  #        clusterServersConfig:
  #          nodeAddresses:
  #            - "redis://${spring.redis.cluster.nodes[0]}"
  #            - "redis://${spring.redis.cluster.nodes[1]}"
  #            - "redis://${spring.redis.cluster.nodes[2]}"
  #          password: ${spring.redis.password}
  #          masterConnectionPoolSize: 64
  #          slaveConnectionPoolSize: 64
  #          idleConnectionTimeout: 10000
  #          connectTimeout: ${spring.redis.timeout}
  #          timeout: ${spring.redis.timeout}



  # 数据源配置
  datasource:
    # 关键：使用 ShardingSphere 驱动
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # 关键：URL 指向独立的规则文件
    url: jdbc:shardingsphere:classpath:sharding.yaml



sharding:
  bucket:
    enabled: true


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: assign_id
  mapper-locations: classpath*:/mapper/**/*.xml

jwt:
  secret: myVerySecureSecretKeyForMatchmakerAideApplicationThatIsAtLeast256BitsLong
  expiration: 7200  # 令牌过期时间（秒），默认2小时

logging:
  level:
    # 观察事务是否创建以及是否正确触发回滚
    org.springframework.transaction: DEBUG
    org.springframework.jdbc.datasource.DataSourceTransactionManager: DEBUG

    # 观察 ShardingSphere 的分片路由和实际执行引擎
    org.apache.shardingsphere.core.route: DEBUG
    org.apache.shardingsphere.core.execute.sql.execute.engine: DEBUG
