server:
  port: 8082

spring:
  application:
    name: money-service
  cloud:
    nacos:
      discovery:
        # 确保这里的地址是实际 Nacos 服务器的地址
        server-addr: ${NACOS_ADDR:192.168.2.20:8848}

  jackson:
    generator:
      write_numbers_as_strings: true

#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://${MYSQL_HOST:192.168.2.20}:3306/matchmaker?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
#    username: root
#    password: 123456

  redis:
    host: ${REDIS_HOST:192.168.2.20}
    port: 6379
    password: ${REDIS_PASSWORD:123456}
    database: 0
    timeout: 3000ms
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
  #  redis:
  #    # 基本配置
  #    cluster:
  #      nodes:
  #        - 192.168.1.101:6379
  #        - 192.168.1.102:6379
  #        - 192.168.1.103:6379
  #      max-redirects: 3
  #    password: "your_password"
  #    timeout: 3000ms
  #
  #    # Redisson 配置
  #    redisson:
  #      config: |
  #        clusterServersConfig:
  #          nodeAddresses:
  #            - "redis://${spring.redis.cluster.nodes[0]}"
  #            - "redis://${spring.redis.cluster.nodes[1]}"
  #            - "redis://${spring.redis.cluster.nodes[2]}"
  #          password: ${spring.redis.password}
  #          masterConnectionPoolSize: 64
  #          slaveConnectionPoolSize: 64
  #          idleConnectionTimeout: 10000
  #          connectTimeout: ${spring.redis.timeout}
  #          timeout: ${spring.redis.timeout}



  # ShardingSphere 配置
  shardingsphere:
    mode:
      type: Memory
#      repository:
#        type: Nacos
#        props:
#          namespace:  # Nacos 命名空间，默认为 public
#          serverList: ${NACOS_ADDR:192.168.2.20:8848}
#          group: SHARDING_SPHERE_DEFAULT_GROUP
#          username: nacos
#          password: nacos
#          timeout: 3000
    # 数据源配置
    datasource:
      names: ds0
#      names: ds0,ds1,ds2

      # 数据源0
      ds0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://${MYSQL_HOST_0:192.168.2.20}:3306/matchmaker?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&autocommit=false
        username: root
        password: 123456
        hikari: #不生效
          auto-commit: false  # 关闭自动提交
          connection-timeout: 30000
          maximum-pool-size: 20
          minimum-idle: 5
          idle-timeout: 600000
          max-lifetime: 1800000
          connection-init-sql: |
            SET autocommit=0;
            SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED;
          transaction-isolation: TRANSACTION_READ_COMMITTED
          pool-name: HikariPool-Sharding
          leak-detection-threshold: 60000
          data-source-properties:
            cachePrepStmts: true
            prepStmtCacheSize: 250
            prepStmtCacheSqlLimit: 2048
            useServerPrepStmts: true
            useLocalSessionState: true
            rewriteBatchedStatements: true
            maintainTimeStats: false
            useLocalTransactionState: true

#      # 数据源1
#      ds1:
#        type: com.zaxxer.hikari.HikariDataSource
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        jdbc-url: jdbc:mysql://${MYSQL_HOST_1:192.168.2.21}:3306/matchmaker_db1?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
#        username: root
#        password: 123456
#
#      # 数据源2（预留，后续扩容启用）
#      ds2:
#        type: com.zaxxer.hikari.HikariDataSource
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        jdbc-url: jdbc:mysql://${MYSQL_HOST_2:192.168.2.22}:3306/matchmaker_db2?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
#        username: root
#        password: 123456

    # 分片规则配置
    rules:
      sharding:
        tables:
          aide_money:
            # 实际数据节点
#              actual-data-nodes: ds$->{0..1}.aide_money
            actual-data-nodes: ds$->{0}.aide_money

            # 分库策略
            database-strategy:
              standard:
                sharding-column: user_id  # 分片键
                sharding-algorithm-name: database-bucket

        # 分片算法配置
        sharding-algorithms:
          # 自定义哈希桶算法
          database-bucket:
            type: CLASS_BASED
            props:
              strategy: standard
              algorithmClassName: com.aide.sharding.algorithm.BucketShardingAlgorithm

    # 其他属性
    props:
      sql-show: true  # 打印实际执行的 SQL
      check-table-metadata-enabled: true  # 检查表元数据
sharding:
  bucket:
    enabled: true
  
  
#  # ShardingSphere 配置
#  shardingsphere:
#    mode:
#      type: Cluster
#    #      repository:
#    #        type: Nacos
#    #        props:
#    #          namespace:  # Nacos 命名空间，默认为 public
#    #          serverList: ${NACOS_ADDR:192.168.2.20:8848}
#    #          group: SHARDING_SPHERE_DEFAULT_GROUP
#    #          username: nacos
#    #          password: nacos
#    #          timeout: 3000
#    # 数据源配置
#    datasource:
#      names: ds0,ds1,ds2
#
#      # 数据源0
#      ds0:
#        type: com.zaxxer.hikari.HikariDataSource
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        jdbc-url: jdbc:mysql://${MYSQL_HOST_0:192.168.2.20}:3306/matchmaker?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
#        username: root
#        password: 123456
#
#      # 数据源1
#      ds1:
#        type: com.zaxxer.hikari.HikariDataSource
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        jdbc-url: jdbc:mysql://${MYSQL_HOST_1:192.168.2.21}:3306/matchmaker_db1?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
#        username: root
#        password: 123456
#
#      # 数据源2（预留，后续扩容启用）
#      ds2:
#        type: com.zaxxer.hikari.HikariDataSource
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        jdbc-url: jdbc:mysql://${MYSQL_HOST_2:192.168.2.22}:3306/matchmaker_db2?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
#        username: root
#        password: 123456
#
#    # 分片规则配置
#    rules:
#      sharding:
#        tables:
#          aide_money:
#            # 实际数据节点
#            #              actual-data-nodes: ds$->{0..1}.aide_money
#            actual-data-nodes: ds$->{0}.aide_money
#
#            # 分库策略
#            database-strategy:
#              standard:
#                sharding-column: user_id  # 分片键
#                sharding-algorithm-name: database-bucket
#
#        # 分片算法配置
#        sharding-algorithms:
#          # 自定义哈希桶算法
#          database-bucket:
#            type: CLASS_BASED
#            props:
#              strategy: standard
#              algorithmClassName: com.aide.sharding.algorithm.BucketShardingAlgorithm
#
#    # 其他属性
#    props:
#      sql-show: true  # 打印实际执行的 SQL
#      check-table-metadata-enabled: true  # 检查表元数据
#sharding:
#  bucket:
#    enabled: true

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: assign_id
  mapper-locations: classpath*:/mapper/**/*.xml

jwt:
  secret: myVerySecureSecretKeyForMatchmakerAideApplicationThatIsAtLeast256BitsLong
  expiration: 7200  # 令牌过期时间（秒），默认2小时

logging:
  level:
#    org.springframework.transaction: DEBUG
    org.apache.shardingsphere: DEBUG
