registry.type=nacos
registry.nacos.serverAddr="192.168.2.20:8848"
registry.nacos.namespace=public
registry.nacos.group=SEATA_GROUP
registry.nacos.cluster=default
registry.nacos.username=nacos
registry.nacos.password=nacos

config.type=nacos
config.nacos.serverAddr="192.168.2.20:8848"
config.nacos.namespace=public
config.nacos.group=SEATA_GROUP
config.nacos.username=nacos
config.nacos.password=nacos
config.nacos.dataId=seata-client.yaml

service.vgroupMapping.default_tx_group=default
service.default.grouplist="192.168.2.20:8091"