# ==================== 客户端配置给 SeataATShardingSphereTransactionManager ====================
client {
  application.id = "member-service"
  transaction.service.group = "default_tx_group"

  rm {
    async.commit.buffer.limit = 10000
    lock {
      retry.interval = 10
      retry.times = 30
    }
    report.retry.count = 5
    table.meta.check.enable = false
    report.success.enable = false
  }

  tm {
    commit.retry.count = 5
    rollback.retry.count = 5
  }

  undo {
    data.validation = true
    log.serialization = "jackson"
    log.table = "undo_log"
  }

  log {
    exceptionRate = 100
  }
}

# ==================== 服务配置 ====================
service {
  vgroupMapping {
    default_tx_group = "default"
  }

  default {
    grouplist = "192.168.2.20:8091"
  }

  enableDegrade = false
  disableGlobalTransaction = false
}

# Seata 1.7.1 FileConfiguration 必须要有 ★★★
registry {
  type = "nacos"
  nacos {
    serverAddr = "192.168.2.20:8848"
    namespace = "public"
    group = "SEATA_GROUP"
    cluster = "default"
    username = "nacos"
    password = "nacos"
    application = "seata-server"
  }
}

config {
  type = "nacos"
  nacos {
    serverAddr = "192.168.2.20:8848"
    namespace = "public"
    group = "SEATA_GROUP"
    username = "nacos"
    password = "nacos"
    data-id = "seata-client.yaml"
  }
}