version: '3.8'

services:
  redis:
    image: redis:7.2
    container_name: redis
    privileged: true
    ports:
      - "6379:6379"
    volumes:
      - /var/redis/redis.conf:/etc/redis/redis.conf
      - /var/redis/data:/data
      - /var/redis/redis.log:/etc/redis.log
    command: ["redis-server", "/etc/redis/redis.conf"]
    networks:
      - mynet

networks:
  mynet:
    external: true