sudo vi /etc/sysconfig/network-scripts/ifcfg-ens33


TYPE="Ethernet"
PROXY_METHOD="none"
BROWSER_ONLY="no"
# BOOTPROTO="dhcp"
BOOTPROTO="static"
DEFROUTE="yes"
IPV4_FAILURE_FATAL="no"
IPV6INIT="yes"
IPV6_AUTOCONF="yes"
IPV6_DEFROUTE="yes"
IPV6_FAILURE_FATAL="no"
IPV6_ADDR_GEN_MODE="stable-privacy"
NAME="ens33"
UUID="0a1865d9-3d49-4076-bb38-bf9772d78f61"
DEVICE="ens33"
ONBOOT="yes"
IPADDR="192.168.2.20"
NETMASK="255.255.255.0"
GATEWAY="192.168.2.1" #修改网关
DNS1="8.8.8.8"
DNS2=192.168.2.1              # 加个路由器当备用 DNS


sudo systemctl restart network