server:
  shutdown: graceful # 开启优雅停机
#  port: 8080
  port: ${SERVER_PORT:9020}

spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      discovery:
#        enabled: true
#        service: orderServer
        server-addr: 127.0.0.1:8848
        cluster-name: ${CLUSTER-NAME:HF}
    gateway:
      routes:
        - id: order-service
#          uri: 127.0.0.1:8080
          uri: lb://order-service
#          断言
          predicates:
            - Path=/order/**

#过滤器的值一样按照 默认过滤器>路由过滤器>全局过滤器
#          过滤器 过滤器过滤器之内按照声明顺序从1递增
          filters:
            - AddRequestHeader=Truth,test1 #1
            - AddRequestHeader=Truth,test2 #2
            - AddRequestHeader=Truth,test3 #3
            - AddRequestHeader=Truth,test4 #4
#          默认过滤器，默认过滤器之内按照声明顺序从1递增
      default-filters:
        - AddRequestHeader=Truth,test1 #1
        - AddRequestHeader=Truth,test2 #2
        - AddRequestHeader=Truth,test3 #3
        - AddRequestHeader=Truth,test4 #4

      # 全局的跨域处理
      globalcors: # 全局的跨域处理
        add-to-simple-url-handler-mapping: true # 解决options请求被拦截问题
        corsConfigurations:
          '[/**]':
            allowedOrigins: # 允许哪些网站的跨域请求
              - "http://localhost:8090"
              - "http://www.leyou.com"
            allowedMethods: # 允许的跨域ajax的请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*" # 允许在请求中携带的头信息
            allowCredentials: true # 是否允许携带cookie
            maxAge: 360000 # 这次跨域检测的有效期

jwt:
  secret: myVerySecureSecretKeyForMatchmakerAideApplicationThatIsAtLeast256BitsLong
  expiration: 7200



