server:
  shutdown: graceful # 开启优雅停机
#  port: 8080
  port: ${SERVER_PORT:9020}

spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      # 确保这里的地址是实际 Nacos 服务器的地址
      server-addr: ${NACOS_ADDR:192.168.2.20:8848}
      discovery:
#        username: nacos  # 根据你的 Nacos 控制台登录账号修改
#        password: nacos  # 根据你的 Nacos 控制台登录密码修改
      # 配置中心
      config:
        import-check:
          enabled: false                # 可选：关闭强制校验
        import:
          # 方式一：使用默认规则拉取（自动拼接为 order-service.yaml）
          - optional:nacos:${spring.application.name}.yaml?refreshEnabled=true

          # 方式二：显式指定拉取特定的配置文件（例如 abcs.yaml）
          # - optional:nacos:abcs.yaml?refreshEnabled=true
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
#          uri: http://localhost:8084
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=1
        - id: user-sms
          uri: lb://user-service
          predicates:
            - Path=/api/sms/**
          filters:
            - StripPrefix=1


        - id: points-service
          uri: lb://points-service
          predicates:
            - Path=/api/points/**
          filters:
            - StripPrefix=1


        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/order/**
          filters:
            - StripPrefix=1


        - id: money-service
          uri: lb://money-service
          predicates:
            - Path=/api/money/**
          filters:
            - StripPrefix=1


        - id: member-service
          uri: lb://member-service
          predicates:
            - Path=/api/member/**
          filters:
            - StripPrefix=1

        - id: coupon-service
          uri: lb://coupon-service
          predicates:
            - Path=/api/coupon/**
          filters:
            - StripPrefix=1

      #          #过滤器的值一样按照 默认过滤器>路由过滤器>全局过滤器
      ##          过滤器 过滤器过滤器之内按照声明顺序从1递增
      #          filters:
      #            - AddRequestHeader=Truth,test1 #1
      #            - AddRequestHeader=Truth,test2 #2
      #            - AddRequestHeader=Truth,test3 #3
      #            - AddRequestHeader=Truth,test4 #4
      ##          默认过滤器，默认过滤器之内按照声明顺序从1递增
      #      default-filters:
      #        - AddRequestHeader=Truth,test1 #1
      #        - AddRequestHeader=Truth,test2 #2
      #        - AddRequestHeader=Truth,test3 #3
      #        - AddRequestHeader=Truth,test4 #4

      # 全局的跨域处理
      globalcors: # 全局的跨域处理
        add-to-simple-url-handler-mapping: true # 解决options请求被拦截问题
        corsConfigurations:
          '[/**]':
            allowedOrigins: # 允许哪些网站的跨域请求
              - "http://localhost:8090"
              - "http://www.abc.com"
            allowedMethods: # 允许的跨域ajax的请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*" # 允许在请求中携带的头信息
            allowCredentials: true # 是否允许携带cookie
            maxAge: 360000 # 这次跨域检测的有效期

  redis:
    host: ${REDIS_HOST:192.168.2.20}
    port: 6379
    password: ${REDIS_PASSWORD:123456}
    database: 0
    timeout: 3000ms
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0



jwt:
  secret: myVerySecureSecretKeyForMatchmakerAideApplicationThatIsAtLeast256BitsLong
  expiration: 7200

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    reactor.netty.http.client: TRACE
#    #生产开启下面的，减少IO
#    org.springframework.cloud.gateway: WARN
#    reactor.netty.http.client: WARN
    com.alibaba.nacos: INFO
  file:
    name: logs/gateway-service.log
  pattern:
    level: "%5p [${spring.application.name},%X{traceId:-}]"
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"



