server:
  port: 8081

spring:
  application:
    name: points-service
  cloud:
    nacos:
      # 确保这里的地址是实际 Nacos 服务器的地址
      server-addr: ${NACOS_ADDR:192.168.2.20:8848}
      discovery:
        username: nacos  # 根据你的 Nacos 控制台登录账号修改
        password: nacos  # 根据你的 Nacos 控制台登录密码修改
      # 配置中心
      config:
        import-check:
          enabled: false                # 可选：关闭强制校验
        import:
          # 方式一：使用默认规则拉取（自动拼接为 order-service.yaml）
          - optional:nacos:${spring.application.name}.yaml?refreshEnabled=true

          # 方式二：显式指定拉取特定的配置文件（例如 abcs.yaml）
          # - optional:nacos:abcs.yaml?refreshEnabled=true

  #MQ配置
  rabbitmq:
    host: 192.168.2.20
    port: 5672
    username: admin
    password: 123456
    virtual-host: /
    # 生产者
    publisher-confirm-type: correlated #开启 Confirm
    publisher-returns: true # 开启 Return（路由失败回调）
    template:
      mandatory: true #Return机制生效
    #消费者
    listener:
      simple:
        acknowledge-mode: manual   # 手动 ACK
        prefetch: 10               # 每次预取多少条
        concurrency: 5             # 最小并发消费者数
        max-concurrency: 20        # 最大并发
        retry:
          enabled: true
          max-attempts: 3
    # 公共配置
    cache:
      connection:
        mode: channel
      channel:
        size: 50
    connection-timeout: 5000

  jackson:
    generator:
      write_numbers_as_strings: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:192.168.2.20}:3306/matchmaker?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

  redis:
    host: ${REDIS_HOST:192.168.2.20}
    port: 6379
    password: ${REDIS_PASSWORD:123456}
    database: 0
    timeout: 3000ms
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: assign_id
  mapper-locations: classpath*:/mapper/**/*.xml

jwt:
  secret: myVerySecureSecretKeyForMatchmakerAideApplicationThatIsAtLeast256BitsLong
  expiration: 7200  # 令牌过期时间（秒），默认2小时


# 日志配置
logging:
  level:
    com.alibaba.nacos: INFO
  #    org.apache.shardingsphere: DEBUG
  file:
    name: logs/order-service.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

